### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by riley0122** [NoahStoessel/cumputer-control#1]
Currently in the frontend the ip 127.0.0.1 is used. 127.0.0.1 is an alias for 0.0.0.0 or more well-known `localhost`, this means that at the current state of the project, it will only work if the frontend is running on the same computer as the backend. Thus rendering the project useless. The IP in the front end should be replaced by a variable that gets determined by `window.location.origin`.

**Comment by NoahStoessel** [comment]
thank you url fix commit coming soon

**Comment by NoahStoessel** [comment]
Fixed with commit: https://github.com/NoahStoessel/cumputer-control/commit/93d6c01f517da693a6fa9997ac4fff1bdae730ca
